name: re-usable flow java maven

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Environment - e2e_integration, s1, s2, s3, s4, all'
        default: 'e2e_integration'
        required: true
        type: string
      scope_name:
        description: 'Type of scoped cases - newfeature_testng, regression_testng, sanity_testng'
        default: 'sanity_testng'
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-jdk-11
    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2g
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          ls
          mvn -ntp -B -q clean test -Dsurefire.suiteXmlFiles=test_control/${{ inputs.environment_name }}/${{ inputs.scope_name }}.xml -Dwebdriver.remote.url=http://selenium:4444/wd/hub
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: html test report - ${{inputs.environment_name}} ${{inputs.scope_name}}
          path: target/results.html