name: re-usable flow java maven

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Environment - e2e_integration, s1, s2, s3, s4, all'
        default: 'e2e_integration'
        required: true
        type: string
      scope_name:
        description: 'Type of scoped cases - newfeature_testng, regression_testng, sanity_testng'
        default: 'sanity_testng'
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -ntp -B -q clean test -Dsurefire.suiteXmlFiles=test_control/${{ inputs.environment_name }}/${{ inputs.scope_name }}.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: html test report - ${{inputs.environment_name}} ${{inputs.scope_name}}
        path: target/results.html
