name: re-usable-workflow

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Environment - e2e_integration, s1, s2, s3, s4, all'
        default: 'e2e_integration'
        required: true
        type: string
      scope_name:
        description: 'Type of scoped cases - newfeature_testng, regression_testng, sanity_testng'
        default: 'sanity_testng'
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: maven
    services:
      selenium:
        image: selenium/hub:latest
        ports:
          - 4444:4444
      chrome:
        image: selenium/node-chrome:latest
        env:
          - SE_EVENT_BUS_HOST=selenium
          - SE_EVENT_BUS_PUBLISH_PORT=4442
          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    steps:
      - name: Check if Selenium Hub is running
        run: curl http://selenium:4444/grid/console