name: re-usable-workflow

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Environment - e2e_integration, s1, s2, s3, s4, all'
        default: 'e2e_integration'
        required: true
        type: string
      scope_name:
        description: 'Type of scoped cases - newfeature_testng, regression_testng, sanity_testng'
        default: 'sanity_testng'
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: maven
    services:  
      hub:
        image: selenium/hub
        ports:
          - "4444:4444"
      node-chrome1:
        image: selenium/node-chrome
        env:
          HUB_HOST: hub
        ports:
          - "5900:5900"
    steps:
      - name: Run ls
        run: |
          ls
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Selenium test
        run: |
          ls
          mvn clean
          mvn -ntp -B -q clean test -Dsurefire.suiteXmlFiles=test_control/${{ inputs.environment_name }}/${{ inputs.scope_name }}.xml -Dwebdriver.remote.url=http://hub:4444/wd/hub -Dbrowser=chrome
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: target-folder
          path: target
